version: '3.8'

services:
  bg-removal-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://atoovis:o7nzxQPS94tfBfJ5@cluster0.jtquyul.mongodb.net/atoovis_image_server
      - CACHE_SIZE=1000
      - OUTPUT_QUALITY=95
      - MAX_WORKERS=1
      - TEMP_DIR=tmp
      - KEEP_TEMP_FILES=False
      - STATIC_DIR=static
      - PORT=3000
    volumes:
      - bg-removal-temp:/tmp
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bg_removal_db

volumes:
  bg-removal-temp:
  mongodb_data:
